[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qsarmil"
version = "1.0.5"
description = "Molecular multi-instance machine learning"
readme = { file = "README.rst", content-type = "text/x-rst" }
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [
  { name = "Dmitry Zankov", email = "dvzankov@gmail.com" }
]

dependencies = [
        "click",
        "rdkit",
        "molfeat",
        "mikit-learn",
        "qsarcons",
]

[project.scripts]
qsarmil = "qsarmil.cli:cli"

[dependency-groups]
dev = ["ruff", "mypy", "pytest", "pytest-cov", "ipython"]

[tool.setuptools.packages.find]
where = ["."]

[tool.mypy]
python_version = "3.10"
files = ["qsarmil"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--cov=qsarmil", "--cov-report=term-missing"]

[tool.coverage.run]
source = ["qsarmil"]

[tool.coverage.report]
fail_under = 100
exclude_lines = ["if __name__ == .__main__.:"]

[tool.ruff]
target-version = "py310"
